apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fs-dd-ingress
spec:
  hosts:
  - {{.clusterDefaultHost}}
  gateways:
  - {{.clusterDefaultGateway}}
  http:
  - match:
    - uri:
        prefix: /fs-dd
    route:
    - destination:
        host: fs-dd
